""""
This code belongs to Ken Taco

"""
import random
import sys
import re
from datetime import datetime


user_age = 0
user_bdy_count = 0
user_bdy_weight = 0
father_present = True
isHoe = False
isAdult = False
cur_date = datetime.now().date().strftime("%d/%m/%Y")
birth_date = input("\nEnter your dob:")
regex_pattern = r"[\s\-\.]"
match = re.search(regex_pattern, birth_date)
if match:
    print("Invalid entry. Try again")
    sys.exit()

chck_birth_date = birth_date.split("/")
chck_cur_date = cur_date.split("/")
chck_gap = int(chck_cur_date[2]) - int(chck_birth_date[2])

user_age = chck_gap
if user_age >= 18:
    isAdult = True
else:
    print("User is underage!")

user_gender = input("Enter your gender").lower()
match user_gender:
    case "male":
        print("Hello king!")
    case "female":
        print("Hello queen!")
    case "nonbinary":
        sys.exit("404: gender not found") 

while True:
    try:
        user_bdy_count = int(input("\nEnter your bodycount:"))
        if user_bdy_count < 0:
            print("Bodycount cannot be negative!")
        else:
            break
    except ValueError:
        print("Please enter a valid number for bodycount.")

def convert_weight(weight, unit):
    global user_bdy_weight
    if unit == "american".lower():
        user_bdy_weight = weight * 0.453592
        return user_bdy_weight
    elif unit == "foreign".lower():
        user_bdy_weight = weight * 2.20462
        return user_bdy_weight
    else:
        raise ValueError("Invalid unit. Please choose 'pounds' or 'foreign units'.") 
    

user_bdy_weight = float(input("Enter your weight:"))
pick_conversion = input("American or foreign units?").lower()
convert_weight(user_bdy_weight, pick_conversion)

father_question =input("What is your relationship with your father?").lower()
bad_relationship = ["bad", "nonexistent", "distant", "strained", "abusive", "neglectful", "absent", "unhealthy", "weak", "negative"]
good_relationship = ["good", "close", "loving", "supportive", "healthy", "strong", "positive", "present"]
nuance_relationship = ["okay", "average", "mediocre", "fair", "so-so", "decent", "passable", "tolerable", "middling", "unremarkable", "neutral", "complicated", "indifferent"]
if father_question in bad_relationship:
        father_present = False
elif father_question in good_relationship or father_question in nuance_relationship:
    father_present = True


'''
Title: Code generated by CLaude Code
Author: Anthropic
Date: 2026
Type: Computer-generated code
Availability: https://claude.ai/
'''

# --- Body count tier ---
if user_bdy_count >= 100:
    print("Bonnie Blue is that you?")
elif user_bdy_count >= 5:
    isHoe = True
    if not isAdult:
        print("Wowza, this early?")
    elif user_bdy_weight >= 90.718474:
        if isAdult:
            print("How?")
        else:
            print("How? And you're underage? Someone call Dr. Phil!")

# --- Father situation ---
if not father_present:
    if user_bdy_count == 0:
        print("Fatherless but a virgin? Interesting.")
    else:
        print("Of course you have no father!")
elif user_bdy_count >= 5:
    print("Your father failed you!")
    isHoe = True

# --- End of AI generated code ---
